export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const UPDATE_MOVIE_CATEGORY = "UPDATE_MOVIE_CATEGORY";

export const UPDATE_MOVIE_LIST = "UPDATE_MOVIE_LIST";
export const FETCHING_MOVIE_LIST = "FETCHING_MOVIE_LIST";
export const MOVIE_LIST_FETCHED = "MOVIE_LIST_FETCHED";
